### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MrDitkovichhh** [Andronian42/spdrFramePoster#12]
Where do I add a film and a service as arguments? I can't find where to put them.

**Comment by Andronian42** [comment]
Sorry for my late response, I need to set up better notifications on my GitHub account.
The `frameposter.py` script has to be run from a command line with this syntax:
> python frameposter.py \<film number\> \<service\>
`<film number>` should be the number corresponding to one of the videos you added to `movies.toml`, a file you'll have to make yourself by copying, renaming, and editing `movies.example.toml`. To be perfectly honest, I hate how complicated I made this to set up, and hope to spend the next few days working on an easier way to set it up, I sincerely apologize for its current state.
`<service>` should be one of the following based on the service you are posting to:
- Twitter - `tw`
- Tumblr - `tu`
- Mastodon - `ma`
- Cohost - `co`
- File (keep the frame in the script folder) - `file`
All of these (except for File) should be set up by entering the appropriate information into `secrets.py`, which should also be copied, renamed, and edited from `secrets.example.py`.
If none of this answers your question, please tell me exactly where you are in the process of setting this up and I'll try and give you more specific direction.

**Comment by Andronian42** [comment]
videos.toml setup has been streamlined (it's only been a few days since June 5th, right?) and I'm going to close this as it hasn't gotten a reply since June. If you still have questions, feel free to reopen.
